name: build

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
  package_sdks:
    needs: create_release
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode_version:
          - 10.3
          - 11.2.1
          - 11.3.1
          - 11.4.1
          - 11.5
          - 11.6
          - 11.7
          - 12.0.1
          - 12.1
          - 12.1.1
          - 12.2
          - 12.3
          - 12.4
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode_version }}.app
      - run: tools/package-sdks.sh
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: apple-sdks-xcode-${{ matrix.xcode_version }}.tar.xz
          asset_name: apple-sdks-xcode-${{ matrix.xcode_version }}.tar.xz
          asset_content_type: application/x-xz
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: apple-sdks-xcode-${{ matrix.xcode_version }}.zip
          asset_name: apple-sdks-xcode-${{ matrix.xcode_version }}.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: apple-sdks-xcode-${{ matrix.xcode_version }}.zstd
          asset_name: apple-sdks-xcode-${{ matrix.xcode_version }}.zstd
          asset_content_type: application/zstd
